package com.invoice.auth.entity;

public enum RoleEnum {
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN,
    ROLE_DRIVER,
    ROLE_PRIME_USER,
    ROLE_APPROVER,
    ROLE_WORKFLOW_USER,
    ROLE_HR,
    ROLE_OPERATIONS,
    ROLE_MAINTENANCE,
    ROLE_MARKETING,
    ROLE_MANAGEMENT,
    ROLE_SUPERVISOR,
    ROLE_DRIVER_LEAD,
    ROLE_MARKETING_LEAD,
    ROLE_SUPERVISOR_LEAD
}
